apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: myacrx.azurecr.io/myapp:1743
        ports:
        - containerPort: 80
        resources:  # Add to comply with policy
          limits:
            cpu: "500m" 
            memory: "512Mi"  