apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: myapp-namespace  # Change this
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx:broken
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"  # Lowered to avoid policy
            cpu: "500m"