apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default  # Ensure this is present
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx  # Replace with your actual image
        ports:
        - containerPort: 80