apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitops-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://dev.azure.com/RichardIgbinoba/GitOpsDemo/_git/gitops-repo
  ref:
    branch: main
  secretRef:
    name: gitops-repo-auth