apiVersion: secrets-store.csi.driver.k8s.io/v1
kind: SecretProviderClass
metadata:
  name: myapp-secrets
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "f689e450-00ae-40f3-800d-c1977284b8a1"  # AKS kubelet client ID
    keyvaultName: "gitopkeyvault"
    objects: |
      array:
        - |
          objectName: database-password
          objectType: secret
          objectVersion: ""
    tenantId: "21fa2414-f872-4c9c-8f18-3ac7919870c1"  # From your AKS identity output