trigger: none
pool:
  vmImage: 'ubuntu-latest'
steps:
- checkout: self
- script: |
    git config --global user.email "email"
    git config --global user.name "username"
    git revert 5ee98fe..HEAD --no-edit  # Revert from 5ee98fe to current HEAD
    git push https://$(System.AccessToken)@dev.azure.com/<orgname>/GitOpsDemo/_git/gitops-repo HEAD:main
  displayName: 'Revert to Working State'